/**
 * Copyright: The PastVu contributors.
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */

const globals = require('globals');
const js = require('@eslint/js');
const jsdocPlugin = require('eslint-plugin-jsdoc');
const jestPlugin = require('eslint-plugin-jest');
const headersPlugin = require('eslint-plugin-headers');

const HEADER_CONTENT = 'Copyright: The PastVu contributors.\nGNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)';

const sharedLanguageOptions = {
    ecmaVersion: 2022,
    sourceType: 'module',
    globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.serviceworker,
        __DEV__: 'readonly',
        ga: 'readonly',
        gtag: 'readonly',
    },
};

module.exports = [
    {
        ignores: [
            '.git/**',
            '.idea/**',
            'babel/output.js',
            'bin/**',
            'logs/**',
            'misc/**',
            'views/**',
            'basepatch/**',
            'public/js/shape2geojson/**',
            // Vendored third-party libs under public/js/lib — explicit per-subdir,
            // since flat config global ignores don't reliably honour `!` negation.
            'public/js/lib/bootstrap/**',
            'public/js/lib/doT.js',
            'public/js/lib/geocoordsparser.js',
            'public/js/lib/highstock/**',
            'public/js/lib/i18next.min.js',
            'public/js/lib/jquery/**',
            'public/js/lib/jsuri.js',
            'public/js/lib/lodash.js',
            'public/js/lib/moment/**',
            'public/js/lib/PubSub.js',
            'public/js/lib/require/**',
            'public/js/lib/socket.io.min.js',
            'public/js/lib/trumbowyg/**',
            'public/js/lib/turf.min.js',
            'public/js/lib/underscore.string.js',
            'public/js/lib/knockout/!(extends.js)*',
            'public/js/lib/leaflet/!(extends)/**',
            'public/js/lib/leaflet/leaflet.min.js',
        ],
    },
    {
        ...js.configs.recommended,
        files: ['**/*.js'],
    },
    jsdocPlugin.configs['flat/recommended'],
    {
        files: ['**/*.js'],
        languageOptions: sharedLanguageOptions,
        linterOptions: {
            reportUnusedDisableDirectives: true,
        },
        plugins: {
            headers: headersPlugin,
        },
        rules: {
            'jsdoc/require-jsdoc': 0,
            'jsdoc/require-param': 0,
            'jsdoc/require-param-description': 0,
            'jsdoc/require-returns': 0,
            'jsdoc/require-returns-description': 0,
            'jsdoc/no-undefined-types': [1, {
                definedTypes: ['ObjectId'],
            }],
            'jsdoc/tag-lines': 0,
            'jsdoc/no-defaults': 0,
            'jsdoc/check-types': 0,
            'jsdoc/no-multi-asterisks': 0,
            'jsdoc/reject-any-type': 0,
            'jsdoc/reject-function-type': 0,

            'strict': [0, 'never'],

            'arrow-body-style': [2, 'as-needed', { requireReturnForObjectLiteral: false }],
            'arrow-parens': [2, 'as-needed'],
            'arrow-spacing': [2, { before: true, after: true }],
            'comma-dangle': [2, {
                arrays: 'always-multiline',
                objects: 'always-multiline',
                imports: 'always-multiline',
                exports: 'always-multiline',
                functions: 'ignore',
            }],
            'constructor-super': 0,
            'generator-star-spacing': [2, {
                before: false,
                after: true,
                method: { before: true, after: true },
            }],
            'no-class-assign': 2,
            'no-confusing-arrow': 0,
            'no-const-assign': 2,
            'no-dupe-class-members': 2,
            'no-duplicate-imports': 0,
            'no-new-symbol': 0,
            'no-restricted-globals': 0,
            'no-restricted-imports': 0,
            'no-this-before-super': 0,
            'no-var': 2,
            'no-useless-computed-key': [2, { enforceForClassMembers: true }],
            'no-useless-constructor': 2,
            'no-useless-rename': 2,
            'object-shorthand': [2, 'always', { avoidQuotes: true }],
            'prefer-arrow-callback': [2, { allowNamedFunctions: true }],
            'prefer-const': [2, { destructuring: 'all', ignoreReadBeforeAssign: true }],
            'prefer-destructuring': 0,
            'prefer-numeric-literals': 2,
            'prefer-spread': 2,
            'prefer-reflect': 0,
            'prefer-rest-params': 2,
            'prefer-template': 0,
            'require-yield': 0,
            'sort-imports': 0,
            'symbol-description': 2,
            'template-curly-spacing': 2,
            'yield-star-spacing': [2, 'after'],

            'accessor-pairs': 0,
            'array-callback-return': 0,
            'block-scoped-var': 0,
            'class-methods-use-this': 0,
            'complexity': [0, 11],
            'consistent-return': 0,
            'curly': [2, 'all'],
            'default-case': 0,
            'default-param-last': 0,
            'dot-notation': 2,
            'dot-location': [2, 'property'],
            'eqeqeq': 2,
            'grouped-accessor-pairs': [2, 'setBeforeGet'],
            'guard-for-in': 2,
            'max-classes-per-file': 0,
            'id-denylist': 0,
            'no-alert': 2,
            'no-caller': 2,
            'no-case-declarations': 0,
            'no-constructor-return': 2,
            'no-div-regex': 2,
            'no-else-return': [2, { allowElseIf: false }],
            'no-empty-function': [2, { allow: ['arrowFunctions'] }],
            'no-extra-label': 2,
            'no-eq-null': 2,
            'no-eval': 2,
            'no-extend-native': 2,
            'no-extra-bind': 2,
            'no-fallthrough': 0,
            'no-floating-decimal': 2,
            'no-global-assign': 2,
            'no-implicit-coercion': 0,
            'no-implied-eval': 2,
            'no-invalid-this': 0,
            'no-iterator': 2,
            'no-labels': [2, { allowLoop: true, allowSwitch: false }],
            'no-lone-blocks': 2,
            'no-loop-func': 0,
            'no-magic-numbers': 0,
            'no-multi-spaces': [2, { ignoreEOLComments: true }],
            'no-multi-str': 2,
            'no-new': 2,
            'no-new-func': 2,
            'no-new-wrappers': 2,
            'no-octal': 2,
            'no-octal-escape': 2,
            'no-param-reassign': 0,
            'no-process-env': 0,
            'no-proto': 2,
            'no-redeclare': [2, { builtinGlobals: true }],
            'no-restricted-properties': [0, [{ object: '_', property: 'chain' }]],
            'no-return-assign': 0,
            'no-return-await': 2,
            'no-script-url': 2,
            'no-self-compare': 2,
            'no-sequences': 2,
            'no-throw-literal': 2,
            'no-unmodified-loop-condition': 2,
            'no-unused-expressions': 0,
            'no-unused-labels': 2,
            'no-useless-call': 0,
            'no-useless-catch': 2,
            'no-useless-escape': 2,
            'no-useless-return': 0,
            'no-void': 2,
            'no-warning-comments': [0, { terms: ['todo', 'fixme', 'xxx'], location: 'start' }],
            'no-with': 2,
            'prefer-named-capture-group': 0,
            'prefer-promise-reject-errors': 2,
            'prefer-regex-literals': 2,
            'radix': 2,
            'require-await': 0,
            'require-unicode-regexp': 0,
            'vars-on-top': 0,
            'wrap-iife': [2, 'outside', { functionPrototypeMethods: true }],
            'yoda': 2,

            'init-declarations': 0,
            'no-delete-var': 2,
            'no-implicit-globals': 2,
            'no-label-var': 2,
            'no-self-assign': [2, { props: true }],
            'no-shadow-restricted-names': 2,
            'no-shadow': [0, { builtinGlobals: true, hoist: 'functions', allow: [] }],
            'no-undef-init': 0,
            'no-undef': 2,
            'no-undefined': 0,
            'no-unused-vars': [2, { vars: 'all', args: 'after-used', caughtErrors: 'none', ignoreRestSiblings: true }],
            // Codebase intentionally nulls out vars at end of scope to release refs for GC.
            'no-useless-assignment': 0,
            'no-use-before-define': [2, { functions: false, classes: true }],

            'for-direction': 2,
            'getter-return': 2,
            'no-async-promise-executor': 2,
            'no-await-in-loop': 0,
            'no-compare-neg-zero': 2,
            'no-cond-assign': [2, 'always'],
            'no-console': 0,
            'no-constant-condition': [2, { checkLoops: false }],
            'no-control-regex': 2,
            'no-debugger': 0,
            'no-dupe-args': 2,
            'no-dupe-else-if': 2,
            'no-dupe-keys': 2,
            'no-duplicate-case': 2,
            'no-empty-character-class': 2,
            'no-empty': [2, { allowEmptyCatch: true }],
            'no-ex-assign': 2,
            'no-extra-boolean-cast': 2,
            'no-extra-parens': [2, 'all', {
                conditionalAssign: false,
                returnAssign: false,
                nestedBinaryExpressions: true,
                enforceForArrowConditionals: true,
                enforceForNewInMemberExpressions: true,
            }],
            'no-extra-semi': 2,
            'no-func-assign': 2,
            'no-import-assign': 2,
            'no-inner-declarations': 2,
            'no-invalid-regexp': 2,
            'no-irregular-whitespace': 2,
            'no-misleading-character-class': 0,
            'no-obj-calls': 2,
            'no-prototype-builtins': 0,
            'no-regex-spaces': 2,
            'no-setter-return': 2,
            'no-sparse-arrays': 2,
            'no-template-curly-in-string': 0,
            'no-unreachable': 2,
            'no-unsafe-finally': 2,
            'no-unsafe-negation': [2, { enforceForOrderingRelations: true }],
            'require-atomic-updates': 0,
            'use-isnan': [2, { enforceForSwitchCase: true, enforceForIndexOf: true }],
            'valid-typeof': 2,
            'no-unexpected-multiline': 2,

            'array-bracket-newline': [2, 'consistent'],
            'array-bracket-spacing': [2, 'never'],
            'array-element-newline': 0,
            'block-spacing': [2, 'never'],
            'brace-style': [2, '1tbs', { allowSingleLine: false }],
            'camelcase': [0, { properties: 'never', ignoreDestructuring: true, allow: [] }],
            'capitalized-comments': [0, 'always', { ignoreInlineComments: true, ignoreConsecutiveComments: true }],
            'comma-spacing': [2, { before: false, after: true }],
            'comma-style': [2, 'last'],
            'computed-property-spacing': [2, 'never', { enforceForClassMembers: true }],
            'consistent-this': 0,
            'eol-last': 2,
            'func-call-spacing': 2,
            'func-name-matching': [2, 'always', { considerPropertyDescriptor: true, includeCommonJSModuleExports: false }],
            'func-names': 0,
            'func-style': 0,
            'function-call-argument-newline': [0, 'consistent'],
            'function-paren-newline': [0, 'multiline'],
            'id-length': 0,
            'indent': [2, 4, {
                SwitchCase: 1,
                VariableDeclarator: 'first',
                outerIIFEBody: 1,
                MemberExpression: 1,
                FunctionDeclaration: { parameters: 'first', body: 1 },
                FunctionExpression: { parameters: 'first', body: 1 },
                CallExpression: { arguments: 1 },
                ArrayExpression: 1,
                ObjectExpression: 1,
                ImportDeclaration: 1,
                flatTernaryExpressions: true,
                ignoreComments: false,
            }],
            'key-spacing': [2, { beforeColon: false, afterColon: true }],
            'keyword-spacing': [2, {
                before: true,
                after: true,
                overrides: {
                    return: { after: true },
                    throw: { after: true },
                    case: { after: true },
                },
            }],
            'line-comment-position': 0,
            'linebreak-style': 0,
            'lines-around-comment': [2, {
                beforeBlockComment: true,
                afterBlockComment: false,
                beforeLineComment: false,
                afterLineComment: false,
                allowBlockStart: true,
                allowBlockEnd: true,
                allowClassStart: true,
                allowClassEnd: true,
                allowObjectStart: true,
                allowObjectEnd: true,
                allowArrayEnd: true,
                applyDefaultIgnorePatterns: true,
            }],
            'lines-between-class-members': [2, 'always', { exceptAfterSingleLine: true }],
            'max-depth': [0, 4],
            'max-len': [2, {
                code: 140,
                comments: 140,
                ignoreUrls: true,
                ignoreStrings: true,
                ignoreComments: false,
                ignoreTrailingComments: true,
                ignoreTemplateLiterals: true,
                ignoreRegExpLiterals: true,
                ignorePattern: '^\\s*if\\s*\\(',
            }],
            'max-lines': [0, { max: 300, skipBlankLines: true, skipComments: true }],
            'max-lines-per-function': [0, { max: 50, skipBlankLines: true, skipComments: true }],
            'max-nested-callbacks': 0,
            'max-params': [0, 3],
            'max-statements': [0, 10],
            'max-statements-per-lines': 0,
            'multiline-comment-style': 0,
            'multiline-ternary': [0, 'always-multiline'],
            'new-cap': [2, { newIsCap: true, capIsNew: false, newIsCapExceptions: ['diff_match_patch'] }],
            'new-parens': 2,
            'newline-per-chained-call': [0, { ignoreChainWithDepth: 3 }],
            'no-array-constructor': 2,
            'no-bitwise': 0,
            'no-continue': 0,
            'no-inline-comments': 0,
            'no-lonely-if': 2,
            'no-mixed-spaces-and-tabs': 2,
            'no-multi-assign': 0,
            'no-multiple-empty-lines': [2, { max: 2, maxEOF: 1, maxBOF: 1 }],
            'no-nested-ternary': 0,
            'no-new-object': 2,
            'no-plusplus': 0,
            'no-restricted-syntax': 0,
            'no-tabs': 2,
            'no-ternary': 0,
            'no-trailing-spaces': 2,
            'no-underscore-dangle': [2, { enforceInMethodNames: false, allow: [
                '__DEV__', '_bsontype', '_parsedUrl', '_nojs', '_id', '__v', '_s',
            ] }],
            'no-unneeded-ternary': [2, { defaultAssignment: false }],
            'no-whitespace-before-property': 2,
            'nonblock-statement-body-position': [2, 'beside'],
            'object-curly-newline': [2, { consistent: true }],
            'object-property-newline': 0,
            'one-var': [2, 'never'],
            'one-var-declaration-per-line': [2, 'always'],
            'operator-assignment': 0,
            'operator-linebreak': [2, 'after', { overrides: { '|>': 'before' } }],
            'padded-blocks': [2, { blocks: 'never', classes: 'never', switches: 'never' }, { allowSingleLineBlocks: false }],
            'padding-line-between-statements': [2,
                { blankLine: 'always', prev: 'directive', next: '*' },
                { blankLine: 'any', prev: 'directive', next: 'directive' },
                { blankLine: 'always', prev: 'import', next: '*' },
                { blankLine: 'any', prev: 'import', next: 'import' },
                { blankLine: 'always', prev: '*', next: ['const', 'let', 'var', 'export'] },
                { blankLine: 'always', prev: ['const', 'let', 'var', 'export'], next: '*' },
                { blankLine: 'any', prev: ['const', 'let', 'var', 'export'], next: ['const', 'let', 'var', 'export'] },
                { blankLine: 'always', prev: '*', next: ['if', 'class', 'for', 'do', 'while', 'switch', 'try', 'iife'] },
                { blankLine: 'always', prev: ['if', 'class', 'for', 'do', 'while', 'switch', 'try', 'iife'], next: '*' },
                { blankLine: 'always', prev: '*', next: 'return' }],
            'prefer-exponentiation-operator': 0,
            'prefer-object-spread': 2,
            'quote-props': [2, 'as-needed', { keywords: false, unnecessary: false, numbers: false }],
            'quotes': [2, 'single', 'avoid-escape'],
            'id-match': 0,
            'implicit-arrow-linebreak': 0,
            'semi-spacing': [2, { before: false, after: true }],
            'semi-style': [2, 'last'],
            'semi': [2, 'always', { omitLastInOneLineBlock: false }],
            'sort-keys': 0,
            'sort-vars': 0,
            'space-before-blocks': 2,
            'space-before-function-paren': [2, { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
            'space-in-parens': [2, 'never'],
            'space-infix-ops': 2,
            'space-unary-ops': 0,
            'spaced-comment': [0, 'always', {
                exceptions: ['-', '+'],
                markers: ['=', '!'],
            }],
            'switch-colon-spacing': [2, { after: true, before: false }],
            'template-tag-spacing': [2, 'never'],
            'unicode-bom': [2, 'never'],
            'wrap-regex': 0,

            'object-curly-spacing': [2, 'always'],
            'headers/header-format': [2, {
                source: 'string',
                style: 'jsdoc',
                content: HEADER_CONTENT,
                trailingNewlines: 2,
            }],
        },
    },
    {
        files: ['public/js/**/*.js'],
        languageOptions: {
            globals: {
                ...globals.jquery,
                ...globals.amd,
            },
        },
        rules: {
            'prefer-arrow-callback': 0,
            'object-shorthand': [2, 'consistent'],
            'no-underscore-dangle': 0,
            'prefer-spread': 0,
            'prefer-rest-params': 0,
        },
    },
    {
        files: ['tests/**/*.js'],
        languageOptions: {
            globals: globals.jest,
        },
    },
    {
        files: ['**/__tests__/*.js', '**/__mocks__/*.js'],
        ...jestPlugin.configs['flat/all'],
        languageOptions: {
            ...jestPlugin.configs['flat/all'].languageOptions,
            globals: {
                ...jestPlugin.configs['flat/all'].languageOptions?.globals,
                ...globals.jest,
            },
        },
        rules: {
            ...jestPlugin.configs['flat/all'].rules,
            'jest/prefer-expect-assertions': [1, { onlyFunctionsWithAsyncKeyword: true }],
            'jest/no-hooks': 0,
            'no-underscore-dangle': [2, { allow: ['_id'] }],
            'jest/max-expects': [1, { max: 10 }],
            'jest/no-untyped-mock-factory': 0,
            'jest/prefer-importing-jest-globals': 0,
            'jest/prefer-ending-with-an-expect': 0,
            // These rules need TypeScript parser services we don't have.
            'jest/no-error-equal': 0,
            'jest/no-unnecessary-assertion': 0,
            'jest/valid-expect-with-promise': 0,
        },
    },
    {
        files: ['config/*example'],
        rules: {
            'headers/header-format': 0,
        },
    },
];
