export default {
    DENY: 'DENY',

    BAD_PARAMS: 'BAD_PARAMS',

    TIMEOUT: 'TIMEOUT',
    UNHANDLED_ERROR: 'UNHANDLED_ERROR',

    NOT_FOUND: 'NOT_FOUND',
    NOT_FOUND_USER: 'NOT_FOUND_USER',
    NO_SUCH_METHOD: 'NO_SUCH_METHOD',
    NO_SUCH_RESOURCE: 'NO_SUCH_RESOURCE',

    INPUT: 'INPUT',
    INPUT_FIELD_REQUIRED: 'INPUT_FIELD_REQUIRED',
    INPUT_LOGIN_REQUIRED: 'INPUT_LOGIN_REQUIRED',
    INPUT_LOGIN_CONSTRAINT: 'INPUT_LOGIN_CONSTRAINT',
    INPUT_PASS_REQUIRED: 'INPUT_PASS_REQUIRED',
    INPUT_EMAIL_REQUIRED: 'INPUT_EMAIL_REQUIRED',

    AUTHENTICATION: 'AUTHENTICATION',
    AUTHENTICATION_REGISTRATION: 'AUTHENTICATION_REGISTRATION',
    AUTHENTICATION_PASSCHANGE: 'AUTHENTICATION_PASSCHANGE',
    AUTHENTICATION_DOESNT_MATCH: 'AUTHENTICATION_DOESNT_MATCH',
    AUTHENTICATION_PASS_WRONG: 'AUTHENTICATION_PASS_WRONG',
    AUTHENTICATION_CURRPASS_WRONG: 'AUTHENTICATION_CURRPASS_WRONG',
    AUTHENTICATION_PASSWORDS_DONT_MATCH: 'AUTHENTICATION_PASSWORDS_DONT_MATCH',
    AUTHENTICATION_MAX_ATTEMPTS: 'AUTHENTICATION_MAX_ATTEMPTS',
    AUTHENTICATION_USER_EXISTS: 'AUTHENTICATION_USER_EXISTS',
    AUTHENTICATION_USER_DOESNT_EXISTS: 'AUTHENTICATION_USER_DOESNT_EXISTS',
    AUTHENTICATION_EMAIL_EXISTS: 'AUTHENTICATION_EMAIL_EXISTS',
    AUTHENTICATION_KEY_DOESNT_EXISTS: 'AUTHENTICATION_KEY_DOESNT_EXISTS'
};