import Utils from '../../commons/Utils';

export default Utils.reflectKeys({
    DENY: null,

    BAD_PARAMS: null,

    TIMEOUT: null,
    UNHANDLED_ERROR: null,

    NOT_FOUND: null,
    NOT_FOUND_USER: null,
    NO_SUCH_METHOD: null,
    NO_SUCH_RESOURCE: null,

    INPUT: null,
    INPUT_FIELD_REQUIRED: null,
    INPUT_LOGIN_REQUIRED: null,
    INPUT_LOGIN_CONSTRAINT: null,
    INPUT_PASS_REQUIRED: null,
    INPUT_EMAIL_REQUIRED: null,

    AUTHENTICATION: null,
    AUTHENTICATION_REGISTRATION: null,
    AUTHENTICATION_PASSCHANGE: null,
    AUTHENTICATION_DOESNT_MATCH: null,
    AUTHENTICATION_PASS_WRONG: null,
    AUTHENTICATION_CURRPASS_WRONG: null,
    AUTHENTICATION_PASSWORDS_DONT_MATCH: null,
    AUTHENTICATION_MAX_ATTEMPTS: null,
    AUTHENTICATION_USER_EXISTS: null,
    AUTHENTICATION_USER_DOESNT_EXISTS: null,
    AUTHENTICATION_EMAIL_EXISTS: null,
    AUTHENTICATION_KEY_DOESNT_EXISTS: null
});