import Utils from '../../commons/Utils';

export default Utils.reflectKeys({
    DENY: null,

    BAD_PARAMS: null,

    TIMEOUT: null,
    UNHANDLED_ERROR: null,
    COUNTER_ERROR: null,

    NOTICE: null,

    NOT_FOUND: null,
    NOT_FOUND_USER: null,
    NO_SUCH_METHOD: null,
    NO_SUCH_RESOURCE: null,
    NO_SUCH_PHOTO: null,
    NO_SUCH_USER: null,
    NO_SUCH_REGION: null,

    INPUT: null,
    INPUT_FIELD_REQUIRED: null,
    INPUT_LOGIN_REQUIRED: null,
    INPUT_LOGIN_CONSTRAINT: null,
    INPUT_PASS_REQUIRED: null,
    INPUT_EMAIL_REQUIRED: null,

    AUTHENTICATION: null,
    AUTHENTICATION_REGISTRATION: null,
    AUTHENTICATION_PASSCHANGE: null,
    AUTHENTICATION_DOESNT_MATCH: null,
    AUTHENTICATION_PASS_WRONG: null,
    AUTHENTICATION_CURRPASS_WRONG: null,
    AUTHENTICATION_PASSWORDS_DONT_MATCH: null,
    AUTHENTICATION_MAX_ATTEMPTS: null,
    AUTHENTICATION_USER_EXISTS: null,
    AUTHENTICATION_USER_DOESNT_EXISTS: null,
    AUTHENTICATION_EMAIL_EXISTS: null,
    AUTHENTICATION_KEY_DOESNT_EXISTS: null,

    PHOTO_CHANGED: null,
    PHOTO_NEED_REASON: null,
    PHOTO_NEED_COORD: null,
    PHOTO_NEED_TITLE: null,
    PHOTO_ANOTHER_STATUS: null,
    PHOTO_YEARS_CONSTRAINT: null,
    PHOTO_CONVERT_PROCEEDING: null,

    HISTORY_DOESNT_EXISTS: null,
});