name: Automerge master to en

on:
  push:
    branches: master

jobs:
  merge-master-to-en:
    # This only makes sense to run for pastvu owned repo.
    if: github.repository_owner == 'pastvu'
    name: Merge master into en
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: merge master into en
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git checkout en
          git merge --no-edit origin/master
          git push origin en