name: Tagged Release

on:
  push:
    tags:
      - '*'
      - '!**-en'

jobs:
  release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

